DOMAIN = "abb_b23_mbus"
CONF_BAUDRATE = 2400
CONF_DEVICE = "/dev/ttyUSB0"
CONF_METER_ADDRESS = "1"
CONF_POLLING_RATE = 60
CONF_MAX_TIMEOUT = 300

MQTT_BROKER = "172.17.1.2"
MQTT_PORT = 1883
MQTT_USER = "hassio"
MQTT_PASSWORD = "RshxJp2zd6"
MQTT_TOPIC = "homeassistant/sensor/abb_b23_mbus"